<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <LangVersion>8.0</LangVersion>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <OutputPath>../1.6/Assemblies</OutputPath>
    <DebugType>none</DebugType>
    <DebugSymbols>false</DebugSymbols>
    <Deterministic>true</Deterministic>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <ManagedDirPath>\Users\boris\Library\Application Support\Steam\steamapps\common\RimWorld\RimWorldMac.app\Contents\Resources\Data\Managed</ManagedDirPath>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Lib.Harmony" Version="2.4.0" IncludeAssets="compile" PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Assembly-CSharp" HintPath="$(ManagedDirPath)\Assembly-CSharp.dll" Private="false" />
    <Reference Include="UnityEngine" HintPath="$(ManagedDirPath)\UnityEngine.dll" Private="false" />
    <Reference Include="UnityEngine.CoreModule" HintPath="$(ManagedDirPath)\UnityEngine.CoreModule.dll" Private="false" />
    <Reference Include="UnityEngine.IMGUIModule" HintPath="$(ManagedDirPath)\UnityEngine.IMGUIModule.dll" Private="false" />
    <Reference Include="UnityEngine.ImageConversionModule" HintPath="$(ManagedDirPath)\UnityEngine.ImageConversionModule.dll" Private="false" />
    <Reference Include="UnityEngine.TextRenderingModule" HintPath="$(ManagedDirPath)\UnityEngine.TextRenderingModule.dll" Private="false" />
    <Reference Include="System.Net.Http" />
  </ItemGroup>

</Project>
